### ISSUE TITLE
Missing settings :datacollector://microsoft/VideoRecorder/1.0

### ISSUE THREAD

**Issue by Hilarius86** [OsirisTerje/RunSettings#3]
Hi,

the documentation has another DataCollector:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017#example-runsettings-file

`      <DataCollector uri="datacollector://microsoft/VideoRecorder/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder.VideoRecorderDataCollector, Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Screen and Voice Recorder">
        
      </DataCollector>`

Maybe add it to the AllSettings template and add the missing variation parameters?

**Comment by OsirisTerje** [comment]
Thanks!   Will do.

**Comment by OsirisTerje** [comment]
Fixed in version 5.5
